### ISSUE TITLE
Build process  doesn't work propertly

### ISSUE THREAD

**Issue by toshovski** [meysholdt/Xpect#162]
I've tried to build Xpect local on my Ubuntu 14.04, but there is a problem with antlr. It doesn't get downloaded and I recieve the following message in a cycle.. 

.....
[INFO] *ATTENTION*
[INFO] It is recommended to use the ANTLR 3 parser generator (BSD licence - http://www.antlr.org/license.html).
[INFO] Do you agree to download it (size 1MB) from 'http://download.itemis.com/antlr-generator-3.2.0.jar'? (type 'y' or 'n' and hit enter)
......

I tried to copy the jar file in each project and rename it to ".antlr-generator-3.2.0.jar", but I get the same message.. any idea, how to fix that problem?

**Comment by meysholdt** [comment]
Hi,

yes, you can integrate Antlr as an update-site/dependency:

It's available as an update site here:
http://download.itemis.com/updates/releases/2.1.1/

**Comment by toshovski** [comment]
Thanks for the feedback. It works! :) 

FYI: 2 tests of xpect nightly are failing.

 [INFO] org.xpect.integrationtest.eclipse_4_4_0.xtext_nightly  FAILURE [10.355s]

Failed tests: 
  DMResourceDescriptionTest>ResourceDescriptionTest.referenceDescriptions:109 expected:<...a.lang.String
/1::/@[]superTypes.0 type --...> but was:<...a.lang.String
/1::/@[annotations.0 annotation --> java:/Objects/java.lang.SuppressWarnings#java.lang.SuppressWarnings
/1::/@]superTypes.0 type --...>
  DMValidationTest>ValidationTest.errors:53 expected:<...inal variable" at "x[ = 2]"
			x = 2
			
			//...> but was:<...inal variable" at "x[]"
			x = 2
			
			//...>

**Comment by meysholdt** [comment]
The failing test has already been set to ignore in 27c857c218df4023f92a18d3dc583e9f95388cbf
