### ISSUE TITLE
Mixed XPECT errors and XPECT warnings confuse the diff

### ISSUE THREAD

**Issue by szarnekow** [meysholdt/Xpect#188]
```
// XPECT errors --> "no viable alternative at input '{'" at "{"
// XPECT warnings --> "Name may be confused with alphabet." at "abc"
val abc{d}
```

the diff suggests that the actual result was

```
// XPECT errors ---
"Name may be confused with alphabet." at "abc"
"no viable alternative at input '{'" at "{"

---
// XPECT warnings ---
"Name may be confused with alphabet." at "abc"
"no viable alternative at input '{'" at "{"

---
val abc{d}
```

**Comment by xpomul** [comment]
I came over this issue as well today. The problem is that if multiple issues of different severities are encountered in the same line, they are all reported as matches.
With my pull request I have added a filter by severity for the issues encountered at the given line.
