### ISSUE TITLE
Prepare Xpect repository for Eclipse initial contribution (1st iteration)

### ISSUE THREAD

**Issue by mor-n4** [meysholdt/Xpect#220]
This includes copyright headers, adding standard files required by Eclipse (e.g. about.html), aligning vendor IDs, etc.

NOTE: this issue covers only a first iteration in order to prepare as much as possible; remaining alignments (e.g. renaming) have to be done later and everything has to be double-checked again right before the initial contribution .zip is being created and submitted (when the Eclipse Xpect project will be created and we can submit CQs).

**Comment by meysholdt** [comment]
merged. Thank you!
